/* eslint-disable */
require('./area')
require('./arrow-right')
require('./catalogobject')
require('./close')
require('./down')
require('./fb')
require('./mail')
require('./password')
require('./phone-call')
require('./point-card')
require('./price')
require('./star')
require('./user')
require('./user2')
require('./vk')
